{
 "title": "Rapyuta IO Devices",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "rr-io-datasource" },
   {
    "name": "rio_project",
    "query": {}
   },
   {
    "name": "device_name",
    "query": {}
   },
   {
    "name": "disk_device",
    "query": {}
   },
   {
    "name": "network_interface",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "filterBys": [
      { "id": "UckXl0P_xfnAMSDt9bi3Z", "key": { "label": "system.device_name", "value": "system.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } }
     ],
     "metricGroup": { "label": "system", "value": "system" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "last", "value": "last" }, "id": "yHF4zwEHyOfCyAVydcGke", "legend": "", "metric_group": { "label": "system.uptime", "value": "system.uptime" } }
     ]
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "filterBys": [
      { "id": "-mcaBjGe2It41BMyQXFZq", "key": { "label": "system.device_name", "value": "system.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } }
     ],
     "metricGroup": { "label": "system", "value": "system" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "last", "value": "last" }, "id": "m1lJCqWympN4AooKlVekG", "legend": "", "metric_group": { "label": "system.n_cpus", "value": "system.n_cpus" } }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU usage percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "FPejne8Tmf88fVVSbj83b", "key": { "label": "cpu.device_name", "value": "cpu.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } },
      { "id": "Q5pA18zmErmYHrftwl410", "key": { "label": "cpu.cpu", "value": "cpu.cpu" }, "value": { "label": "cpu-total", "value": "cpu-total" } }
     ],
     "metricGroup": { "label": "cpu", "value": "cpu" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "average", "value": "avg" }, "id": "o7ixcn5dacsvoOFZyHTqc", "legend": "", "metric_group": { "label": "cpu.usage_idle", "value": "cpu.usage_idle" } }
     ]
    }
   ]
  },
  {
   "title": "[WIP] CPU usage per core",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "FPejne8Tmf88fVVSbj83b", "key": { "label": "cpu.device_name", "value": "cpu.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } }
     ],
     "groupBys": [
      { "groupBy": { "label": "cpu.cpu", "value": "cpu.cpu" }, "id": "z61-AaREdflwD56ub40m_" }
     ],
     "metricGroup": { "label": "cpu", "value": "cpu" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "average", "value": "avg" }, "id": "o7ixcn5dacsvoOFZyHTqc", "legend": "", "metric_group": { "label": "cpu.usage_idle", "value": "cpu.usage_idle" } }
     ]
    }
   ]
  },
  {
   "title": "CPU metrics ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "filterBys": [
      { "id": "1AZx7cJIJW_08qdQHoLa3", "key": { "label": "cpu.device_name", "value": "cpu.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } }
     ],
     "metricGroup": { "label": "cpu", "value": "cpu" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "average", "value": "avg" }, "id": "ke-lM2s_Rlh16Eny00dIe", "legend": "", "metric_group": { "label": "cpu.usage_user", "value": "cpu.usage_user" } },
      { "aggregation": { "label": "max", "value": "max" }, "id": "xQTyxo1amqY6k90OcTMBG", "legend": "", "metric_group": { "label": "cpu.usage_user", "value": "cpu.usage_user" } },
      { "aggregation": { "label": "average", "value": "avg" }, "id": "OH3yzNh2hhT1uMzy2eQq-", "legend": "", "metric_group": { "label": "cpu.usage_system", "value": "cpu.usage_system" } },
      { "aggregation": { "label": "max", "value": "max" }, "id": "xlMK1YB6onVb3jfRdZRrh", "legend": "", "metric_group": { "label": "cpu.usage_system", "value": "cpu.usage_system" } }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "iMOlKMGOiIIF_pTtOZau_", "key": { "label": "mem.device_name", "value": "mem.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } }
     ],
     "metricGroup": { "label": "mem", "value": "mem" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "average", "value": "avg" }, "id": "iD8upqQ0ULd2o-8e4Uk-J", "legend": "", "metric_group": { "label": "mem.total", "value": "mem.total" } },
      { "aggregation": { "label": "average", "value": "avg" }, "id": "FgMZ5jrNhOvxinRytPI-L", "legend": "", "metric_group": { "label": "mem.available", "value": "mem.available" } }
     ]
    }
   ]
  },
  {
   "title": "Memory usage percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "iMOlKMGOiIIF_pTtOZau_", "key": { "label": "mem.device_name", "value": "mem.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } }
     ],
     "metricGroup": { "label": "mem", "value": "mem" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "average", "value": "avg" }, "id": "iD8upqQ0ULd2o-8e4Uk-J", "legend": "", "metric_group": { "label": "mem.total", "value": "mem.total" } },
      { "aggregation": { "label": "average", "value": "avg" }, "id": "FgMZ5jrNhOvxinRytPI-L", "legend": "", "metric_group": { "label": "mem.available", "value": "mem.available" } }
     ]
    }
   ]
  },
  { "title": "Block Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "JUv5abJmQw8HyVyyoxZCH", "key": { "label": "disk.device_name", "value": "disk.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } },
      { "id": "b1UGWTXLB2Bj-eo4C_6uH", "key": { "label": "disk.path", "value": "disk.path" }, "value": { "label": "/", "value": "/" } }
     ],
     "metricGroup": { "label": "disk", "value": "disk" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "average", "value": "avg" }, "id": "GHVOgZAEXn4hibfPPdrD4", "legend": "", "metric_group": { "label": "disk.total", "value": "disk.total" } },
      { "aggregation": { "label": "average", "value": "avg" }, "id": "BN1hOBGOwfmIwKeLQiMPA", "legend": "", "metric_group": { "label": "disk.used", "value": "disk.used" } }
     ]
    }
   ]
  },
  {
   "title": "Disk usage percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "JUv5abJmQw8HyVyyoxZCH", "key": { "label": "disk.device_name", "value": "disk.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } },
      { "id": "sBLbQwACwLBqdiCl2UBOG", "key": { "label": "disk.path", "value": "disk.path" }, "value": { "label": "/", "value": "/" } }
     ],
     "metricGroup": { "label": "disk", "value": "disk" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "average", "value": "avg" }, "id": "GHVOgZAEXn4hibfPPdrD4", "legend": "", "metric_group": { "label": "disk.total", "value": "disk.total" } },
      { "aggregation": { "label": "average", "value": "avg" }, "id": "BN1hOBGOwfmIwKeLQiMPA", "legend": "", "metric_group": { "label": "disk.used", "value": "disk.used" } }
     ]
    }
   ]
  },
  {
   "title": "Disk inode usage percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "UlvmFKxORN6HrJh6mj5vz", "key": { "label": "disk.device_name", "value": "disk.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } },
      { "id": "emtJfK0a1MhWJwZpzAp3i", "key": { "label": "disk.path", "value": "disk.path" }, "value": { "label": "/", "value": "/" } }
     ],
     "metricGroup": { "label": "disk", "value": "disk" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "average", "value": "avg" }, "id": "pZX76hfkVzBqM8V1woQOm", "legend": "", "metric_group": { "label": "disk.inodes_total", "value": "disk.inodes_total" } },
      { "aggregation": { "label": "average", "value": "avg" }, "id": "tR-AOYlDxBh4kH73YVpke", "legend": "", "metric_group": { "label": "disk.inodes_used", "value": "disk.inodes_used" } }
     ]
    }
   ]
  },
  {
   "title": "Disk read and write rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "FjhJuMCoL16DtY5P9rYMx", "key": { "label": "diskio.device_name", "value": "diskio.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } },
      { "id": "Spv9Q9REFU42C1h4POORT", "key": { "label": "diskio.name", "value": "diskio.name" }, "value": { "label": "$disk_device", "value": "$disk_device" } }
     ],
     "metricGroup": { "label": "diskio", "value": "diskio" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "derivative", "value": "derivative" }, "id": "mvTVb6IvrQOSEm78hs44h", "legend": "", "metric_group": { "label": "diskio.write_bytes", "value": "diskio.write_bytes" } }
     ]
    },
    {
     "filterBys": [
      { "id": "qugfFD8HqEDtnQItdNY2I", "key": { "label": "diskio.device_name", "value": "diskio.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } },
      { "id": "N-TgxuQ4jC7vC1EEeyglH", "key": { "label": "diskio.name", "value": "diskio.name" }, "value": { "label": "$disk_device", "value": "$disk_device" } }
     ],
     "metricGroup": { "label": "diskio", "value": "diskio" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "derivative", "value": "derivative" }, "id": "oh5pMh4WEbYsl17ROXwA8", "legend": "", "metric_group": { "label": "diskio.read_bytes", "value": "diskio.read_bytes" } }
     ]
    }
   ]
  },
  {
   "title": "Disk read and write latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "FjhJuMCoL16DtY5P9rYMx", "key": { "label": "diskio.device_name", "value": "diskio.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } },
      { "id": "Spv9Q9REFU42C1h4POORT", "key": { "label": "diskio.name", "value": "diskio.name" }, "value": { "label": "$disk_device", "value": "$disk_device" } }
     ],
     "metricGroup": { "label": "diskio", "value": "diskio" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "derivative", "value": "derivative" }, "id": "mvTVb6IvrQOSEm78hs44h", "legend": "", "metric_group": { "label": "diskio.write_time", "value": "diskio.write_time" } }
     ]
    },
    {
     "filterBys": [
      { "id": "qugfFD8HqEDtnQItdNY2I", "key": { "label": "diskio.device_name", "value": "diskio.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } },
      { "id": "N-TgxuQ4jC7vC1EEeyglH", "key": { "label": "diskio.name", "value": "diskio.name" }, "value": { "label": "$disk_device", "value": "$disk_device" } }
     ],
     "metricGroup": { "label": "diskio", "value": "diskio" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "derivative", "value": "derivative" }, "id": "oh5pMh4WEbYsl17ROXwA8", "legend": "", "metric_group": { "label": "diskio.read_time", "value": "diskio.read_time" } }
     ]
    }
   ]
  },
  {
   "title": "Disk io latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "qugfFD8HqEDtnQItdNY2I", "key": { "label": "diskio.device_name", "value": "diskio.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } },
      { "id": "N-TgxuQ4jC7vC1EEeyglH", "key": { "label": "diskio.name", "value": "diskio.name" }, "value": { "label": "$disk_device", "value": "$disk_device" } }
     ],
     "metricGroup": { "label": "diskio", "value": "diskio" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "derivative", "value": "derivative" }, "id": "oh5pMh4WEbYsl17ROXwA8", "legend": "", "metric_group": { "label": "diskio.io_time", "value": "diskio.io_time" } }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Network read and write rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "4Jx6ougcfit9iFAQt7k6s", "key": { "label": "net.device_name", "value": "net.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } },
      { "id": "oay7Grl4wQMJH2MI3KThY", "key": { "label": "net.interface", "value": "net.interface" }, "value": { "label": "$network_interface", "value": "$network_interface" } }
     ],
     "metricGroup": { "label": "net", "value": "net" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "derivative", "value": "derivative" }, "id": "eqblgXQqp3wcU0p5Bjckx", "legend": "", "metric_group": { "label": "net.bytes_recv", "value": "net.bytes_recv" } }
     ]
    },
    {
     "filterBys": [
      { "id": "eyQQT4ouXvZfmqW05hF-p", "key": { "label": "net.device_name", "value": "net.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } },
      { "id": "yvEwwZ-QMuV5_agPndN1R", "key": { "label": "net.interface", "value": "net.interface" }, "value": { "label": "$network_interface", "value": "$network_interface" } }
     ],
     "metricGroup": { "label": "net", "value": "net" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "derivative", "value": "derivative" }, "id": "MHVOHHdfGF3oxyQsqGbIV", "legend": "", "metric_group": { "label": "net.bytes_sent", "value": "net.bytes_sent" } }
     ]
    }
   ]
  },
  {
   "title": "Network receive and sent dropped packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "4Jx6ougcfit9iFAQt7k6s", "key": { "label": "net.device_name", "value": "net.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } },
      { "id": "oay7Grl4wQMJH2MI3KThY", "key": { "label": "net.interface", "value": "net.interface" }, "value": { "label": "$network_interface", "value": "$network_interface" } }
     ],
     "metricGroup": { "label": "net", "value": "net" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "derivative", "value": "derivative" }, "id": "eqblgXQqp3wcU0p5Bjckx", "legend": "", "metric_group": { "label": "net.drop_in", "value": "net.drop_in" } }
     ]
    },
    {
     "filterBys": [
      { "id": "eyQQT4ouXvZfmqW05hF-p", "key": { "label": "net.device_name", "value": "net.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } },
      { "id": "yvEwwZ-QMuV5_agPndN1R", "key": { "label": "net.interface", "value": "net.interface" }, "value": { "label": "$network_interface", "value": "$network_interface" } }
     ],
     "metricGroup": { "label": "net", "value": "net" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "derivative", "value": "derivative" }, "id": "MHVOHHdfGF3oxyQsqGbIV", "legend": "", "metric_group": { "label": "net.drop_out", "value": "net.drop_out" } }
     ]
    }
   ]
  },
  {
   "title": "Network receive and sent errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "4Jx6ougcfit9iFAQt7k6s", "key": { "label": "net.device_name", "value": "net.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } },
      { "id": "oay7Grl4wQMJH2MI3KThY", "key": { "label": "net.interface", "value": "net.interface" }, "value": { "label": "$network_interface", "value": "$network_interface" } }
     ],
     "metricGroup": { "label": "net", "value": "net" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "derivative", "value": "derivative" }, "id": "eqblgXQqp3wcU0p5Bjckx", "legend": "", "metric_group": { "label": "net.err_in", "value": "net.err_in" } }
     ]
    },
    {
     "filterBys": [
      { "id": "eyQQT4ouXvZfmqW05hF-p", "key": { "label": "net.device_name", "value": "net.device_name" }, "value": { "label": "$device_name", "value": "$device_name" } },
      { "id": "yvEwwZ-QMuV5_agPndN1R", "key": { "label": "net.interface", "value": "net.interface" }, "value": { "label": "$network_interface", "value": "$network_interface" } }
     ],
     "metricGroup": { "label": "net", "value": "net" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "derivative", "value": "derivative" }, "id": "MHVOHHdfGF3oxyQsqGbIV", "legend": "", "metric_group": { "label": "net.err_out", "value": "net.err_out" } }
     ]
    }
   ]
  },
  { "title": "Wireless", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Signal strength",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "filterBys": [
      {
       "id": "md2bn6fnNHdm889GsKod7",
       "key": { "label": "wireless.device_name", "value": "wireless.device_name" },
       "value": { "label": "$device_name", "value": "$device_name" }
      },
      { "id": "0kon62tE9xnkScR5d1qMI", "key": { "label": "wireless.interface", "value": "wireless.interface" }, "value": { "label": "$network_interface", "value": "$network_interface" } }
     ],
     "metricGroup": { "label": "wireless", "value": "wireless" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "average", "value": "avg" }, "id": "E4pUO9YA2n81l1kiG0iFx", "legend": "", "metric_group": { "label": "wireless.level", "value": "wireless.level" } }
     ]
    }
   ]
  },
  {
   "title": "Noise level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "filterBys": [
      {
       "id": "md2bn6fnNHdm889GsKod7",
       "key": { "label": "wireless.device_name", "value": "wireless.device_name" },
       "value": { "label": "$device_name", "value": "$device_name" }
      },
      { "id": "0kon62tE9xnkScR5d1qMI", "key": { "label": "wireless.interface", "value": "wireless.interface" }, "value": { "label": "$network_interface", "value": "$network_interface" } }
     ],
     "metricGroup": { "label": "wireless", "value": "wireless" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "average", "value": "avg" }, "id": "E4pUO9YA2n81l1kiG0iFx", "legend": "", "metric_group": { "label": "wireless.noise", "value": "wireless.noise" } }
     ]
    }
   ]
  },
  {
   "title": "Link quality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "filterBys": [
      {
       "id": "md2bn6fnNHdm889GsKod7",
       "key": { "label": "wireless.device_name", "value": "wireless.device_name" },
       "value": { "label": "$device_name", "value": "$device_name" }
      },
      { "id": "0kon62tE9xnkScR5d1qMI", "key": { "label": "wireless.interface", "value": "wireless.interface" }, "value": { "label": "$network_interface", "value": "$network_interface" } }
     ],
     "metricGroup": { "label": "wireless", "value": "wireless" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "average", "value": "avg" }, "id": "E4pUO9YA2n81l1kiG0iFx", "legend": "", "metric_group": { "label": "wireless.link", "value": "wireless.link" } }
     ]
    }
   ]
  },
  {
   "title": "Cumulative packet retries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filterBys": [
      {
       "id": "md2bn6fnNHdm889GsKod7",
       "key": { "label": "wireless.device_name", "value": "wireless.device_name" },
       "value": { "label": "$device_name", "value": "$device_name" }
      },
      { "id": "0kon62tE9xnkScR5d1qMI", "key": { "label": "wireless.interface", "value": "wireless.interface" }, "value": { "label": "$network_interface", "value": "$network_interface" } }
     ],
     "metricGroup": { "label": "wireless", "value": "wireless" },
     "metricType": { "label": "System", "value": "system" },
     "metrics": [
      { "aggregation": { "label": "average", "value": "avg" }, "id": "E4pUO9YA2n81l1kiG0iFx", "legend": "", "metric_group": { "label": "wireless.retry", "value": "wireless.retry" } }
     ]
    }
   ]
  },
  {
   "title": "BSSID",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "WuUpUB02HL_D6en0gX95v", "key": { "label": "spidermon.host", "value": "spidermon.host" }, "value": { "label": "$device_name", "value": "$device_name" } }
     ],
     "groupBys": [
      {
       "groupBy": { "label": "spidermon.bssid_name", "value": "spidermon.bssid_name" },
       "id": "myvMLS6J1bWbsMI0iWAyZ"
      }
     ],
     "metricGroup": { "label": "spidermon", "value": "spidermon" },
     "metricType": { "label": "User", "value": "user" },
     "metrics": [
      { "aggregation": { "label": "average", "value": "avg" }, "id": "ddd5NoNIR1dyqVp6kdz2q", "legend": "{{ bssid_name }}", "metric_group": { "label": "spidermon.bssid", "value": "spidermon.bssid" } }
     ]
    }
   ]
  },
  {
   "title": "[WIP] No. of devices connected to each BSSID",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBys": [
      {
       "groupBy": { "label": "spidermon.bssid_name", "value": "spidermon.bssid_name" },
       "id": "DOxUnK5lZi83fQxtxaftW"
      }
     ],
     "metricGroup": { "label": "spidermon", "value": "spidermon" },
     "metricType": { "label": "User", "value": "user" },
     "metrics": [
      { "aggregation": { "label": "distinct", "value": "distinct" }, "id": "v_3UXWYSULUxLhvTjeGPY", "legend": "", "metric_group": { "label": "spidermon.bssid", "value": "spidermon.bssid" } }
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "AeDzQdFhIcuXYbZQB-ze4", "key": { "label": "spidermon.host", "value": "spidermon.host" }, "value": { "label": "$device_name", "value": "$device_name" } }
     ],
     "metricGroup": { "label": "spidermon", "value": "spidermon" },
     "metricType": { "label": "User", "value": "user" },
     "metrics": [
      { "aggregation": { "label": "average", "value": "avg" }, "id": "u_tHrTXW_vuLMfBSjFiE9", "legend": "", "metric_group": { "label": "spidermon.rssi", "value": "spidermon.rssi" } }
     ]
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "tEA7NFWYSVHYbOVd1es0y", "key": { "label": "spidermon.host", "value": "spidermon.host" }, "value": { "label": "$device_name", "value": "$device_name" } }
     ],
     "metricGroup": { "label": "spidermon", "value": "spidermon" },
     "metricType": { "label": "User", "value": "user" },
     "metrics": [
      { "aggregation": { "label": "average", "value": "avg" }, "id": "JqRIFlYjT2aPMZWc48xTz", "legend": "frequency", "metric_group": { "label": "spidermon.freq", "value": "spidermon.freq" } }
     ]
    }
   ]
  },
  {
   "title": "Ping Internal",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "UmzEP1VFnrlqPwPcakMnU", "key": { "label": "spidermon.host", "value": "spidermon.host" }, "value": { "label": "$device_name", "value": "$device_name" } }
     ],
     "metricGroup": { "label": "spidermon", "value": "spidermon" },
     "metricType": { "label": "User", "value": "user" },
     "metrics": [
      {
       "aggregation": { "label": "average", "value": "avg" },
       "id": "VDlPwh4P7E-fehCXkASA3",
       "legend": "",
       "metric_group": { "label": "spidermon.ping_internal", "value": "spidermon.ping_internal" }
      }
     ]
    }
   ]
  },
  {
   "title": "Ping External",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "Zwo8pVr4Q3hyc6aTThIbG", "key": { "label": "spidermon.host", "value": "spidermon.host" }, "value": { "label": "$device_name", "value": "$device_name" } }
     ],
     "metricGroup": { "label": "spidermon", "value": "spidermon" },
     "metricType": { "label": "User", "value": "user" },
     "metrics": [
      {
       "aggregation": { "label": "average", "value": "avg" },
       "id": "MuxTgDTJTAOJzCpBrQrqw",
       "legend": "",
       "metric_group": { "label": "spidermon.ping_external", "value": "spidermon.ping_external" }
      }
     ]
    }
   ]
  },
  {
   "title": "Failure Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filterBys": [
      { "id": "6aPH4UOxvqvLwT_wLT8Hp", "key": { "label": "spidermon.host", "value": "spidermon.host" }, "value": { "label": "$device_name", "value": "$device_name" } }
     ],
     "metricGroup": { "label": "spidermon", "value": "spidermon" },
     "metricType": { "label": "User", "value": "user" },
     "metrics": [
      { "aggregation": { "label": "average", "value": "avg" }, "id": "Ve5WDqxisN0eELszPo3O2", "legend": "", "metric_group": { "label": "spidermon.freq", "value": "spidermon.freq" } }
     ]
    }
   ]
  },
  {
   "title": "[WIP] Disconnection Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricGroup": { "label": "spidermon", "value": "spidermon" },
     "metricType": { "label": "User", "value": "user" },
     "metrics": [
      { "aggregation": { "label": "average", "value": "avg" }, "id": "l18S6OkSQOuCO4r10xPw7", "legend": "" }
     ]
    }
   ]
  }
 ]
}